schema_version: 1

context:
  name: factur-x
  version: "6.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 37d07a8f281e397d6eda17f620f871b51132c87a47b5955412007b52fed501e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - hatchling
    - hatch-requirements-txt
  run:
    - python >=${{ python_min }}
    - pypdf >=5.3.0
    - lxml
    - python-stdnum
    - requests
tests:
  - python:
      imports:
        - facturx
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: 'Factur-X and Order-X: electronic invoicing and ordering standards'
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/akretion/factur-x

extra:
  recipe-maintainers:
    - jan-janssen
